version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: '10:00'
    open-pull-requests-limit: 10
