linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 26
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 165
  funlen:
    lines: 80
  gomoddirectives:
    replace-local: true
  ireturn:
    allow: "error,empty,Module"
linters:
  enable-all: true
  fast: false
  disable:
    - gci
    - gofumpt
    - godot
    - cyclop
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - golint
    - ifshort
    - interfacer
    - maligned
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - varcheck
    - wsl
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "`noCopy` is unused"
    - "mnd: Magic number: 0.001, in"
    - "mnd: Magic number: 2, in"
    - "mnd: Magic number: 3, in"
    - "mnd: Magic number: 4, in"
    - "mnd: Magic number: 5, in"
    - "mnd: Magic number: 6, in"
    - "mnd: Magic number: 7, in"
    - "mnd: Magic number: 10, in"
    - "mnd: Magic number: 14, in"
    - "mnd: Magic number: 15, in"
    - "mnd: Magic number: 16, in"
    - "mnd: Magic number: 20, in"
    - "mnd: Magic number: 24, in"
    - "mnd: Magic number: 32, in"
    - "mnd: Magic number: 50, in"
    - "mnd: Magic number: 60, in"
    - "mnd: Magic number: 64, in"
    - "mnd: Magic number: 100, in"
    - "mnd: Magic number: 126, in"
    - "mnd: Magic number: 127, in"
    - "mnd: Magic number: 365, in"
    - "mnd: Magic number: 500, in"
    - "mnd: Magic number: 512, in"
    - "mnd: Magic number: 1000, in"
    - "mnd: Magic number: 1024, in"
    - "mnd: Magic number: 3600, in"
    - "mnd: Magic number: 86400, in"
    - "mnd: Magic number: 1e3, in"
    - "mnd: Magic number: 1e6, in"
    - "mnd: Magic number: 1e9, in"
    - "mnd: Magic number: 1e12, in"
    - "mnd: Magic number: 1e15, in"
    - "mnd: Magic number: 0o600, in"
    - "noCopy is missing in"
    - 'err113:'
    - "variable name 'ok' is too short"
    - "Function 'setListenConfig' has too many statements"
    - "Function 'ParseArgs' has too many statements"
    - "complexity.*setListenConfig"
    - "complexity.*checkFlags"
    - "Function 'readConfiguration' has too many statements"
    - "complexity.*readConfiguration"
    - "Function 'Check' has too many statements"
    - "Function 'Check' is too long"
    - "cognitive complexity .* of func .*.Check"
    - "cognitive complexity .* of func .*conditionAdd"
    - "cognitive complexity .* of func .*.matchSingle"
    - "Function 'matchSingle' has too many statements"
    - "cyclomatic complexity .* of func .*.matchSingle"
    - "Function 'ParseINI' has too many statements"
    - "cognitive complexity .* of func .*ParseINI`"
    - "cognitive complexity .* of func .*ThresholdString"
    - "appendAssign: append result not assigned to the same slice"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupword
