linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 27
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 200
  funlen:
    lines: 80
    statements: 45
  gomoddirectives:
    replace-local: true
  ireturn:
    allow: "error,empty,Module,CheckHandler"
  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - Tracef
          - Infof
          - Warnf
          - Errorf
          - Fatalf
          - Criticalf
          - Panicf
linters:
  enable-all: true
  fast: false
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - err113
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gofumpt
    - gomoddirectives
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    # deprecated
    - tenv
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: true
  exclude:
    - "`noCopy` is unused"
    - "Magic number: 0.1, in"
    - "Magic number: 0.01, in"
    - "Magic number: 0.001, in"
    - "Magic number: 2, in"
    - "Magic number: 3, in"
    - "Magic number: 4, in"
    - "Magic number: 5, in"
    - "Magic number: 6, in"
    - "Magic number: 7, in"
    - "Magic number: 10, in"
    - "Magic number: 12, in"
    - "Magic number: 14, in"
    - "Magic number: 15, in"
    - "Magic number: 16, in"
    - "Magic number: 20, in"
    - "Magic number: 22, in"
    - "Magic number: 23, in"
    - "Magic number: 24, in"
    - "Magic number: 31, in"
    - "Magic number: 32, in"
    - "Magic number: 50, in"
    - "Magic number: 59, in"
    - "Magic number: 60, in"
    - "Magic number: 64, in"
    - "Magic number: 100, in"
    - "Magic number: 126, in"
    - "Magic number: 127, in"
    - "Magic number: 365, in"
    - "Magic number: 500, in"
    - "Magic number: 512, in"
    - "Magic number: 600, in"
    - "Magic number: 1000, in"
    - "Magic number: 1024, in"
    - "Magic number: 3600, in"
    - "Magic number: 86400, in"
    - "Magic number: 1e3, in"
    - "Magic number: 1e6, in"
    - "Magic number: 1e7, in"
    - "Magic number: 1e9, in"
    - "Magic number: 1e12, in"
    - "Magic number: 1e15, in"
    - "Magic number: 0o600, in"
    - "Magic number: 0o700, in"
    - "noCopy is missing in"
    - "variable name 'ok' is too short"
    - "Function 'setListenTLSConfig' has too many statements"
    - "Function 'ParseArgs' has too many statements"
    - "Function 'parseAnyArg' has too many statements"
    - "complexity.*setListenTLSConfig"
    - "complexity.*checkFlags"
    - "complexity.*ParseArgs"
    - "Function 'readConfiguration' has too many statements"
    - "complexity.*readConfiguration"
    - "Function 'Check' has too many statements"
    - "Function 'Check' is too long"
    - "Function 'fetchProcs' is too long"
    - "Function 'buildListMacros' is too long"
    - "Function 'fetchProcs' has too many statements"
    - "Function 'ReplaceConditionals' has too many statements"
    - "cognitive complexity .* of func .*.Check"
    - "cognitive complexity .* of func .*conditionAdd"
    - "cognitive complexity .* of func .*.matchSingle"
    - "cognitive complexity .* of func .*splitToken"
    - "cognitive complexity .* of func .*ReplaceConditionals"
    - "Function 'matchSingle' has too many statements"
    - "cyclomatic complexity .* of func .*.matchSingle"
    - "Function 'ParseINI' has too many statements"
    - "Function 'buildListMacros' has too many statements"
    - "Function 'finalizeOutput' has too many statements"
    - "Function 'addFile' has too many statements"
    - "cognitive complexity .* of func .*ParseINI`"
    - "cognitive complexity .* of func .*ThresholdString"
    - "appendAssign: append result not assigned to the same slice"
    - "parameter name 'a' is too short for the scope of its usage"
    - "parameter name 'b' is too short for the scope of its usage"
    - ".execCommand` - `timeout` always receives `DefaultCmdTimeout"
    - "fieldalignment: struct"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test.*\.go
      linters:
        - dupword
        - funlen
        - copyloopvar
    - path: (check_tcp|check_dns|nameserver.*)\.go
      linters:
        - nolintlint
