version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - embeddedstructfieldcheck
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godoclint
    - gomoddirectives
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    - wsl_v5
  settings:
    funlen:
      lines: 80
      statements: 45
    goconst:
      min-len: 8
      min-occurrences: 12
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 27
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - Tracef
            - Infof
            - Warnf
            - Errorf
            - Fatalf
            - Criticalf
            - Panicf
    ireturn:
      allow:
        - error
        - empty
        - Module
        - CheckHandler
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - copyloopvar
          - dupword
          - funlen
        path: _test.*\.go
      - linters:
          - nolintlint
        path: (check_tcp|check_dns|nameserver.*)\.go
      - path: (.+)\.go$
        text: '`noCopy` is unused'
      - path: (.+)\.go$
        text: 'Magic number: 0.1, in'
      - path: (.+)\.go$
        text: 'Magic number: 0.01, in'
      - path: (.+)\.go$
        text: 'Magic number: 0.001, in'
      - path: (.+)\.go$
        text: 'Magic number: 2, in'
      - path: (.+)\.go$
        text: 'Magic number: 3, in'
      - path: (.+)\.go$
        text: 'Magic number: 4, in'
      - path: (.+)\.go$
        text: 'Magic number: 5, in'
      - path: (.+)\.go$
        text: 'Magic number: 6, in'
      - path: (.+)\.go$
        text: 'Magic number: 7, in'
      - path: (.+)\.go$
        text: 'Magic number: 10, in'
      - path: (.+)\.go$
        text: 'Magic number: 12, in'
      - path: (.+)\.go$
        text: 'Magic number: 14, in'
      - path: (.+)\.go$
        text: 'Magic number: 15, in'
      - path: (.+)\.go$
        text: 'Magic number: 16, in'
      - path: (.+)\.go$
        text: 'Magic number: 20, in'
      - path: (.+)\.go$
        text: 'Magic number: 22, in'
      - path: (.+)\.go$
        text: 'Magic number: 23, in'
      - path: (.+)\.go$
        text: 'Magic number: 24, in'
      - path: (.+)\.go$
        text: 'Magic number: 31, in'
      - path: (.+)\.go$
        text: 'Magic number: 32, in'
      - path: (.+)\.go$
        text: 'Magic number: 50, in'
      - path: (.+)\.go$
        text: 'Magic number: 59, in'
      - path: (.+)\.go$
        text: 'Magic number: 60, in'
      - path: (.+)\.go$
        text: 'Magic number: 64, in'
      - path: (.+)\.go$
        text: 'Magic number: 100, in'
      - path: (.+)\.go$
        text: 'Magic number: 126, in'
      - path: (.+)\.go$
        text: 'Magic number: 127, in'
      - path: (.+)\.go$
        text: 'Magic number: 365, in'
      - path: (.+)\.go$
        text: 'Magic number: 500, in'
      - path: (.+)\.go$
        text: 'Magic number: 512, in'
      - path: (.+)\.go$
        text: 'Magic number: 600, in'
      - path: (.+)\.go$
        text: 'Magic number: 1000, in'
      - path: (.+)\.go$
        text: 'Magic number: 1024, in'
      - path: (.+)\.go$
        text: 'Magic number: 3600, in'
      - path: (.+)\.go$
        text: 'Magic number: 86400, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e3, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e6, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e7, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e9, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e12, in'
      - path: (.+)\.go$
        text: 'Magic number: 1e15, in'
      - path: (.+)\.go$
        text: 'Magic number: 0o600, in'
      - path: (.+)\.go$
        text: 'Magic number: 0o700, in'
      - path: (.+)\.go$
        text: noCopy is missing in
      - path: (.+)\.go$
        text: variable name 'ok' is too short
      - path: (.+)\.go$
        text: Function 'setListenTLSConfig' has too many statements
      - path: (.+)\.go$
        text: Function 'ParseArgs' has too many statements
      - path: (.+)\.go$
        text: 'cyclomatic complexity 45 of func `.*\.parseArgs` is high'
      - path: (.+)\.go$
        text: Function 'parseArgs' has too many statements
      - path: (.+)\.go$
        text: Function 'parseAnyArg' has too many statements
      - path: (.+)\.go$
        text: complexity.*setListenTLSConfig
      - path: (.+)\.go$
        text: complexity.*checkFlags
      - path: (.+)\.go$
        text: complexity.*ParseArgs
      - path: (.+)\.go$
        text: Function 'readConfiguration' has too many statements
      - path: (.+)\.go$
        text: complexity.*readConfiguration
      - path: (.+)\.go$
        text: Function 'Check' has too many statements
      - path: (.+)\.go$
        text: Function 'Check' is too long
      - path: (.+)\.go$
        text: Function 'fetchProcs' is too long
      - path: (.+)\.go$
        text: Function 'buildListMacros' is too long
      - path: (.+)\.go$
        text: Function 'fetchProcs' has too many statements
      - path: (.+)\.go$
        text: Function 'ReplaceConditionals' has too many statements
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*.Check
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*conditionAdd
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*.matchSingle
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*splitToken
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*ReplaceConditionals
      - path: (.+)\.go$
        text: Function 'matchSingle' has too many statements
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func .*.matchSingle
      - path: (.+)\.go$
        text: Function 'ParseINI' has too many statements
      - path: (.+)\.go$
        text: Function 'buildListMacros' has too many statements
      - path: (.+)\.go$
        text: Function 'finalizeOutput' has too many statements
      - path: (.+)\.go$
        text: Function 'addFile' has too many statements
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*ParseINI`
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func .*ParseINI`
      - path: (.+)\.go$
        text: cognitive complexity .* of func .*ThresholdString
      - path: (.+)\.go$
        text: 'appendAssign: append result not assigned to the same slice'
      - path: (.+)\.go$
        text: parameter name 'a' is too short for the scope of its usage
      - path: (.+)\.go$
        text: parameter name 'b' is too short for the scope of its usage
      - path: (.+)\.go$
        text: .execCommand` - `timeout` always receives `DefaultCmdTimeout
      - path: (.+)\.go$
        text: 'fieldalignment: struct'
      - path: (.+)(utils|utils_test|fieldsn|asciiTable)\.go$
        text: 'var-naming: avoid meaningless package names'
      - path: (.+)_test\.go$
        text: 'stringsbuilder:'
      - path: (.+)\.go$
        text: timeout always receives DefaultCmdTimeout
      - path: (.+)_test\.go$
        text: 'must not be called. use'
      - path: (.+)\.go$
        text: 'fmtappendf:'
      - path: (.+)_test\.go$
        text: 'string literal contains rune in Han script'
      - path: (.+)condition\.go$
        text: 'stringscutprefix:'
    paths:
      - pkg/pdh/pdh.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/pdh/pdh.go
      - third_party$
      - builtin$
      - examples$
