#!/bin/bash

if [ ! -e .git ]; then
    echo "not in an development environment, no .git directory found" >&2
    exit 1
fi

# find an exact match, if found use that one
VERSION=`git describe --tag --exact-match 2>/dev/null`
if [ $? -eq 0 ]; then
    echo ${VERSION#"v"}
    exit 0
fi

LASTTAG=$(git describe --tags --abbrev=0 2>/dev/null)
if [ -z $LASTTAG ]; then
    # no tag yet
    COMMITS=$(printf "%04d" $( git rev-list --all --count ))
    echo 0.01.${COMMITS}
else
    # there is a tag
    COMMITS=$(printf "%04d" $(git log ${LASTTAG}..HEAD --oneline | wc -l))
    echo ${LASTTAG#"v"}.${COMMITS}
fi
