#!/bin/sh

if [ ! -e .git ]; then
    echo "not in an development environment, no .git directory found" >&2
    exit 1
fi

# anything but the main branch gets a "dev" version to separate it from official versions
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# find an exact match, if found use that one
VERSION=$(git describe --tag --exact-match 2>/dev/null)
if [ $? -eq 0 ]; then
    echo ${VERSION#"v"}
    COMMITS=$(printf "%05d" $( git rev-list --all --count ))
    exit 0
fi

LASTTAG=$(git describe --tags --abbrev=0 2>/dev/null)
if [ -z "$LASTTAG" -o "x$BRANCH" != "xmain" ]; then
    # no tag yet
    COMMITS=$(printf "%05d" $( git rev-list --all --count ))
    echo 0.01.${COMMITS}
else
    # there is a tag
    COMMITS=$(printf "%04d" $(git log ${LASTTAG}..HEAD --oneline | wc -l))
    echo ${LASTTAG#"v"}.${COMMITS}
fi
