#!/bin/bash
set -e

if [[ ! -d /var/log/snclient ]]; then
  mkdir /var/log/snclient
fi

case "$1" in
    configure|abort-upgrade)
      chmod 0600 \
        /etc/snclient/snclient.ini \
        /etc/snclient/server.key \
        /etc/snclient/server.crt \
        /etc/snclient/cacert.pem \
        > /dev/null || :
      if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper unmask snclient.service
        if deb-systemd-helper --quiet was-enabled snclient.service; then
          deb-systemd-helper enable snclient.service
        else
          deb-systemd-helper update-state snclient.service
        fi
      fi

      systemctl --system daemon-reload >/dev/null || true
      deb-systemd-invoke start snclient
    ;;

    abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
