#!/bin/bash
set -e

if [[ ! -d /var/log/snclient ]]; then
  mkdir /var/log/snclient
fi

# remove previous auto updates
rm -rf /var/cache/snclient/snclient.update
rm -rf /var/cache/snclient/snclient

case "$1" in
    configure|abort-upgrade)
      chmod 0600 \
        /etc/snclient/snclient.ini \
        /etc/snclient/server.key \
        /etc/snclient/server.crt \
        /etc/snclient/cacert.pem \
        || :
      if [ -x "/usr/bin/systemd-sysusers" ]; then
          systemd-sysusers
      else
          # Create snclient group if it doesn't exist
          if ! getent group snclient >/dev/null; then
            addgroup -S snclient
          fi

          # Create snclient user if it doesn't exist
          if ! getent passwd snclient >/dev/null; then
            adduser --system --disabled-password --no-create-home --home /var/lib/snclient --shell /sbin/nologin --group snclient --comment "Secure Naemon Client" snclient
          fi
      fi
      if [ -x "/usr/bin/systemd-tmpfiles" ]; then
          systemd-tmpfiles --create
      else
          # Create and set permissions on directories
          install -d -m 0755 -o snclient -g snclient /etc/snclient
          install -d -m 0755 -o snclient -g snclient /var/lib/snclient
          install -d -m 0755 -o snclient -g snclient /var/log/snclient

          # Fix ownership of config files
          chown -h snclient:snclient \
                /etc/snclient \
                /etc/snclient/cacert.pem \
                /etc/snclient/server.crt \
                /etc/snclient/server.key \
                /etc/snclient/snclient.ini
      fi
      if [ -x "/usr/bin/deb-systemd-helper" ] && [ -x "/usr/bin/systemctl" ] ; then
        deb-systemd-helper unmask snclient.service
        if deb-systemd-helper --quiet was-enabled snclient.service; then
          deb-systemd-helper enable snclient.service
        else
          deb-systemd-helper update-state snclient.service
        fi
      fi

      # Fix ownership of log file
      chown -h snclient:snclient /var/log/snclient/snclient.log 2>/dev/null || true

      if command -v setcap >/dev/null; then
        setcap "cap_setuid,cap_setgid+ep" /usr/bin/snclient || true
      fi

      if [ -x "/usr/bin/systemctl" ] ; then
        systemctl --system daemon-reload >/dev/null 2>&1 || true
        deb-systemd-invoke start snclient
      fi
      update-rc.d snclient defaults
    ;;

    abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
