#!/sbin/openrc-run

description="SNClient+ (Secure Naemon Client)"
supervisor="supervise-daemon"
command="/usr/bin/snclient"
command_args="--config /etc/snclient/snclient.ini"
command_args_background="--pidfile ${pidfile} daemon"
command_user="root:root"
pidfile="/var/run/snclient.pid"

reload() {
  ebegin "Reloading acpid configuration"
  ${supervisor} ${RC_SVCNAME} --signal HUP --pidfile "${pidfile}"
  eend $?
}

depend() {
    need net
}
