name: create windows installer

on: [push]


jobs:
  create-windows-installer:
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - name: Build exe file
        run: |
          choco install make
          go get github.com/mh-cbon/go-msi
          make build-windows-amd64
          go-msi make --msi snclient.msi --version 0.0.1

      - name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'snclient.exe'
